tap "cloudfoundry/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "pivotal/tap"
cask "java"
brew "ant"
brew "docker", restart_service: true
brew "docker-compose", link: false
brew "docker-machine", restart_service: true
brew "docker-machine-driver-xhyve"
brew "git"
brew "git-secret"
brew "gradle"
brew "htop"
brew "hub"
brew "kubernetes-cli"
brew "maven"
brew "node", link: false
brew "openshift-cli"
brew "sbt"
brew "sonar-scanner"
brew "tree"
brew "wget"
brew "xhyve"
brew "cloudfoundry/tap/bosh-cli"
brew "cloudfoundry/tap/cf-cli"
cask "android-ndk"
cask "android-sdk"
cask "android-studio"
cask "blisk"
cask "cheatsheet"
cask "firefox"
cask "fish"
cask "gimp"
cask "google-chrome"
cask "intellij-idea-ce"
cask "iterm2"
cask "minikube"
cask "postman"
cask "spotify"
cask "sublime-text"
